/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as WorkspaceThreadsRouteImport } from './routes/_workspace/threads'
import { Route as WorkspaceKanbanRouteImport } from './routes/_workspace/kanban'
import { Route as WorkspaceDocsRouteImport } from './routes/_workspace/docs'
import { Route as AppCommitRouteImport } from './routes/_app/commit'
import { Route as AppReviewIndexRouteImport } from './routes/_app/review/index'
import { Route as AppBrowseIndexRouteImport } from './routes/_app/browse/index'
import { Route as AppReviewPullRouteImport } from './routes/_app/review/$pull'
import { Route as AppBrowseRangeRouteImport } from './routes/_app/browse/range'
import { Route as AppBrowseCommitShaRouteImport } from './routes/_app/browse/commit.$sha'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const WorkspaceThreadsRoute = WorkspaceThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceKanbanRoute = WorkspaceKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDocsRoute = WorkspaceDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => WorkspaceRoute,
} as any)
const AppCommitRoute = AppCommitRouteImport.update({
  id: '/commit',
  path: '/commit',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewIndexRoute = AppReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseIndexRoute = AppBrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewPullRoute = AppReviewPullRouteImport.update({
  id: '/review/$pull',
  path: '/review/$pull',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseRangeRoute = AppBrowseRangeRouteImport.update({
  id: '/browse/range',
  path: '/browse/range',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseCommitShaRoute = AppBrowseCommitShaRouteImport.update({
  id: '/browse/commit/$sha',
  path: '/browse/commit/$sha',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/commit': typeof AppCommitRoute
  '/docs': typeof WorkspaceDocsRoute
  '/kanban': typeof WorkspaceKanbanRoute
  '/threads': typeof WorkspaceThreadsRoute
  '/browse/range': typeof AppBrowseRangeRoute
  '/review/$pull': typeof AppReviewPullRoute
  '/browse/': typeof AppBrowseIndexRoute
  '/review/': typeof AppReviewIndexRoute
  '/browse/commit/$sha': typeof AppBrowseCommitShaRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/commit': typeof AppCommitRoute
  '/docs': typeof WorkspaceDocsRoute
  '/kanban': typeof WorkspaceKanbanRoute
  '/threads': typeof WorkspaceThreadsRoute
  '/browse/range': typeof AppBrowseRangeRoute
  '/review/$pull': typeof AppReviewPullRoute
  '/browse': typeof AppBrowseIndexRoute
  '/review': typeof AppReviewIndexRoute
  '/browse/commit/$sha': typeof AppBrowseCommitShaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_app/commit': typeof AppCommitRoute
  '/_workspace/docs': typeof WorkspaceDocsRoute
  '/_workspace/kanban': typeof WorkspaceKanbanRoute
  '/_workspace/threads': typeof WorkspaceThreadsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/browse/range': typeof AppBrowseRangeRoute
  '/_app/review/$pull': typeof AppReviewPullRoute
  '/_app/browse/': typeof AppBrowseIndexRoute
  '/_app/review/': typeof AppReviewIndexRoute
  '/_app/browse/commit/$sha': typeof AppBrowseCommitShaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commit'
    | '/docs'
    | '/kanban'
    | '/threads'
    | '/browse/range'
    | '/review/$pull'
    | '/browse/'
    | '/review/'
    | '/browse/commit/$sha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commit'
    | '/docs'
    | '/kanban'
    | '/threads'
    | '/browse/range'
    | '/review/$pull'
    | '/browse'
    | '/review'
    | '/browse/commit/$sha'
  id:
    | '__root__'
    | '/_app'
    | '/_workspace'
    | '/_app/commit'
    | '/_workspace/docs'
    | '/_workspace/kanban'
    | '/_workspace/threads'
    | '/_app/'
    | '/_app/browse/range'
    | '/_app/review/$pull'
    | '/_app/browse/'
    | '/_app/review/'
    | '/_app/browse/commit/$sha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_workspace/threads': {
      id: '/_workspace/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof WorkspaceThreadsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/kanban': {
      id: '/_workspace/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof WorkspaceKanbanRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/docs': {
      id: '/_workspace/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof WorkspaceDocsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_app/commit': {
      id: '/_app/commit'
      path: '/commit'
      fullPath: '/commit'
      preLoaderRoute: typeof AppCommitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review/': {
      id: '/_app/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof AppReviewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/': {
      id: '/_app/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof AppBrowseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review/$pull': {
      id: '/_app/review/$pull'
      path: '/review/$pull'
      fullPath: '/review/$pull'
      preLoaderRoute: typeof AppReviewPullRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/range': {
      id: '/_app/browse/range'
      path: '/browse/range'
      fullPath: '/browse/range'
      preLoaderRoute: typeof AppBrowseRangeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/commit/$sha': {
      id: '/_app/browse/commit/$sha'
      path: '/browse/commit/$sha'
      fullPath: '/browse/commit/$sha'
      preLoaderRoute: typeof AppBrowseCommitShaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCommitRoute: typeof AppCommitRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBrowseRangeRoute: typeof AppBrowseRangeRoute
  AppReviewPullRoute: typeof AppReviewPullRoute
  AppBrowseIndexRoute: typeof AppBrowseIndexRoute
  AppReviewIndexRoute: typeof AppReviewIndexRoute
  AppBrowseCommitShaRoute: typeof AppBrowseCommitShaRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommitRoute: AppCommitRoute,
  AppIndexRoute: AppIndexRoute,
  AppBrowseRangeRoute: AppBrowseRangeRoute,
  AppReviewPullRoute: AppReviewPullRoute,
  AppBrowseIndexRoute: AppBrowseIndexRoute,
  AppReviewIndexRoute: AppReviewIndexRoute,
  AppBrowseCommitShaRoute: AppBrowseCommitShaRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceDocsRoute: typeof WorkspaceDocsRoute
  WorkspaceKanbanRoute: typeof WorkspaceKanbanRoute
  WorkspaceThreadsRoute: typeof WorkspaceThreadsRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceDocsRoute: WorkspaceDocsRoute,
  WorkspaceKanbanRoute: WorkspaceKanbanRoute,
  WorkspaceThreadsRoute: WorkspaceThreadsRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
